coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 1%
    patch:
      default:
        target: 80%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
  - "examples/"
  - "arepy/engine/"
  - "arepy/event_manager/"
  - "arepy/math/"
  - "arepy/container.py"
