from enum import IntFlag
from os import PathLike
from typing import Protocol


class WindowFlag(IntFlag):
    VSYNC_HINT = 0x0040
    FULLSCREEN_MODE = 0x0002
    WINDOW_RESIZABLE = 0x0004
    WINDOW_UNDECORATED = 0x0008
    WINDOW_HIDDEN = 0x0080
    WINDOW_MINIMIZED = 0x0200
    WINDOW_MAXIMIZED = 0x0400
    WINDOW_UNFOCUSED = 0x0800
    WINDOW_TOPMOST = 0x1000
    WINDOW_ALWAYS_RUN = 0x0100
    WINDOW_TRANSPARENT = 0x0010
    WINDOW_HIGHDPI = 0x2000
    WINDOW_MOUSE_PASSTHROUGH = 0x4000
    MSAA_4X_HINT = 0x0020
    INTERLACED_HINT = 0x10000
    BORDERLESS_WINDOWED_MODE = 0x8000


class Display(Protocol):

    def create_window(self, width: int, height: int, title: str) -> None: ...
    def window_should_close(self) -> bool: ...
    def destroy_window(self) -> None: ...
    def set_window_size(self, width: int, height: int) -> None: ...
    def get_window_size(self) -> tuple[int, int]: ...
    def get_window_position(self) -> tuple[int, int]: ...
    def toggle_fullscreen(self) -> None: ...
    def hide_cursor(self) -> None: ...
    def show_cursor(self) -> None: ...
    def is_cursor_hidden(self) -> bool: ...
    def is_fullscreen(self) -> bool: ...
    def set_window_title(self, title: str) -> None: ...
    def set_window_icon(self, path: PathLike[str]) -> None: ...
    def set_window_position(self, x: int, y: int) -> None: ...
    def set_vsync(self, enabled: bool) -> None: ...

    def is_window_resized(self) -> bool: ...
    def set_window_min_size(self, width: int, height: int) -> None: ...
    def set_window_max_size(self, width: int, height: int) -> None: ...
    def set_window_state(self, flags: int) -> None: ...
    def clear_window_state(self, flags: int) -> None: ...
    def is_window_state(self, flag: int) -> bool: ...

    def maximize_window(self) -> None: ...
    def minimize_window(self) -> None: ...
    def restore_window(self) -> None: ...
    def is_window_maximized(self) -> bool: ...
    def is_window_minimized(self) -> bool: ...
    def is_window_focused(self) -> bool: ...
    def set_window_focused(self) -> None: ...
    def is_window_hidden(self) -> bool: ...
    def set_window_opacity(self, opacity: float) -> None: ...
    def get_window_scale_dpi(self) -> tuple[float, float]: ...
    def toggle_borderless(self) -> None: ...
